"""破茧三刀_新增动态发现字段

Revision ID: 116f3df30673
Revises: 001
Create Date: 2026-08-06 18:58:13.741454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '116f3df30673'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_ids', sa.JSON(), nullable=True),
    sa.Column('context_ids', sa.JSON(), nullable=True),
    sa.Column('entity_ids', sa.JSON(), nullable=True),
    sa.Column('skill_ids', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('chart_count', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('parent_context_id', sa.String(length=36), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('visualization_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structured_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_structured_insights_document_id')
        batch_op.drop_index('ix_structured_insights_id')
        batch_op.drop_index('ix_structured_insights_project_id')
        batch_op.drop_index('ix_structured_insights_topics')

    op.drop_table('structured_insights')
    with op.batch_alter_table('fact_statements', schema=None) as batch_op:
        batch_op.drop_index('idx_fact_document')
        batch_op.drop_index('idx_fact_project_topic')
        batch_op.drop_index('idx_fact_speaker')
        batch_op.drop_index('idx_fact_statements_doc')
        batch_op.drop_index('idx_fact_statements_doc_topic')
        batch_op.drop_index('idx_fact_statements_document')
        batch_op.drop_index('idx_fact_statements_topic')
        batch_op.drop_index('idx_fact_statements_unique')
        batch_op.drop_index('ix_fact_statements_document_id')
        batch_op.drop_index('ix_fact_statements_id')
        batch_op.drop_index('ix_fact_statements_project_id')
        batch_op.drop_index('ix_fact_statements_source_file')
        batch_op.drop_index('ix_fact_statements_speaker')
        batch_op.drop_index('ix_fact_statements_topic_tag')

    op.drop_table('fact_statements')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index('idx_analysis_created')
        batch_op.drop_index('idx_analysis_project')
        batch_op.drop_index('idx_analysis_type')

    op.drop_table('analysis_results')
    with op.batch_alter_table('source_verifications', schema=None) as batch_op:
        batch_op.drop_index('idx_verification_source')

    op.drop_table('source_verifications')
    with op.batch_alter_table('statement_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_source_chunk')
        batch_op.drop_index('idx_source_document')
        batch_op.drop_index('idx_source_statement')

    op.drop_table('statement_sources')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_chunks_chunk_id')
        batch_op.drop_index('idx_chunks_document')
        batch_op.drop_index('idx_chunks_project')

    op.drop_table('document_chunks')
    with op.batch_alter_table('analysis_statements', schema=None) as batch_op:
        batch_op.drop_index('idx_statement_analysis')

    op.drop_table('analysis_statements')
    with op.batch_alter_table('topic_statistics', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_statistics_id')
        batch_op.drop_index('ix_topic_statistics_project_id')
        batch_op.drop_index('ix_topic_statistics_topic')

    op.drop_table('topic_statistics')
    with op.batch_alter_table('entity_evidences', schema=None) as batch_op:
        batch_op.drop_index('idx_entity_evidence_category')
        batch_op.drop_index('idx_entity_evidence_chunk')
        batch_op.drop_index('idx_entity_evidence_document')
        batch_op.drop_index('idx_entity_evidence_entity')
        batch_op.drop_index('ix_entity_evidences_chunk_id')
        batch_op.drop_index('ix_entity_evidences_document_id')
        batch_op.drop_index('ix_entity_evidences_entity_id')

    op.drop_table('entity_evidences')
    with op.batch_alter_table('entity_statistics', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_statistics_entity_name')
        batch_op.drop_index('ix_entity_statistics_entity_type')
        batch_op.drop_index('ix_entity_statistics_id')
        batch_op.drop_index('ix_entity_statistics_project_id')

    op.drop_table('entity_statistics')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_entities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('auto_clusters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_profile', sa.JSON(), nullable=True))
        batch_op.drop_index('idx_documents_file_type')
        batch_op.drop_index('idx_documents_status')
        batch_op.drop_index('idx_documents_status_uploaded')
        batch_op.drop_index('idx_documents_uploaded_at')
        batch_op.drop_index('idx_documents_uploaded_by')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('idx_entities_name')
        batch_op.drop_index('idx_entities_type')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_created')
        batch_op.drop_index('idx_projects_owner')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_username')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_username', ['username'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_projects_created', ['created_at'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('idx_entities_type', ['entity_type'], unique=False)
        batch_op.create_index('idx_entities_name', ['name'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_uploaded_by', ['uploaded_by'], unique=False)
        batch_op.create_index('idx_documents_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index('idx_documents_status_uploaded', ['status', 'uploaded_at'], unique=False)
        batch_op.create_index('idx_documents_status', ['status'], unique=False)
        batch_op.create_index('idx_documents_file_type', ['file_type'], unique=False)
        batch_op.drop_column('data_profile')
        batch_op.drop_column('auto_clusters')
        batch_op.drop_column('extracted_entities')

    op.create_table('entity_statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_statistics', schema=None) as batch_op:
        batch_op.create_index('ix_entity_statistics_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_entity_statistics_id', ['id'], unique=False)
        batch_op.create_index('ix_entity_statistics_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_entity_statistics_entity_name', ['entity_name'], unique=False)

    op.create_table('entity_evidences',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp_start', sa.FLOAT(), nullable=True),
    sa.Column('timestamp_end', sa.FLOAT(), nullable=True),
    sa.Column('timestamp_display', sa.VARCHAR(length=50), nullable=True),
    sa.Column('speaker', sa.VARCHAR(length=200), nullable=True),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('position_start', sa.INTEGER(), nullable=True),
    sa.Column('position_end', sa.INTEGER(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_evidences', schema=None) as batch_op:
        batch_op.create_index('ix_entity_evidences_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_entity_evidences_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_entity_evidences_chunk_id', ['chunk_id'], unique=False)
        batch_op.create_index('idx_entity_evidence_entity', ['entity_id'], unique=False)
        batch_op.create_index('idx_entity_evidence_document', ['document_id'], unique=False)
        batch_op.create_index('idx_entity_evidence_chunk', ['chunk_id'], unique=False)
        batch_op.create_index('idx_entity_evidence_category', ['category'], unique=False)

    op.create_table('topic_statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_statistics', schema=None) as batch_op:
        batch_op.create_index('ix_topic_statistics_topic', ['topic'], unique=False)
        batch_op.create_index('ix_topic_statistics_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_topic_statistics_id', ['id'], unique=False)

    op.create_table('analysis_statements',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('statement_text', sa.TEXT(), nullable=False),
    sa.Column('statement_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('section', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_statements', schema=None) as batch_op:
        batch_op.create_index('idx_statement_analysis', ['analysis_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('chunk_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('text_length', sa.INTEGER(), nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), nullable=True),
    sa.Column('start_pos', sa.INTEGER(), nullable=True),
    sa.Column('end_pos', sa.INTEGER(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('chunk_metadata', sqlite.JSON(), nullable=True),
    sa.Column('prev_chunk_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('next_chunk_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('vectorized_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_chunks_project', ['project_id'], unique=False)
        batch_op.create_index('idx_chunks_document', ['document_id'], unique=False)
        batch_op.create_index('idx_chunks_chunk_id', ['chunk_id'], unique=False)

    op.create_table('statement_sources',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('statement_id', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_chunk_id', sa.INTEGER(), nullable=True),
    sa.Column('source_document_id', sa.INTEGER(), nullable=True),
    sa.Column('position_info', sqlite.JSON(), nullable=True),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('quoted_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['project_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['analysis_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statement_sources', schema=None) as batch_op:
        batch_op.create_index('idx_source_statement', ['statement_id'], unique=False)
        batch_op.create_index('idx_source_document', ['source_document_id'], unique=False)
        batch_op.create_index('idx_source_chunk', ['source_chunk_id'], unique=False)

    op.create_table('source_verifications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('statement_source_id', sa.INTEGER(), nullable=False),
    sa.Column('verified_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['statement_source_id'], ['statement_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_verification_source', ['statement_source_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('analysis_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_type', ['analysis_type'], unique=False)
        batch_op.create_index('idx_analysis_project', ['project_id'], unique=False)
        batch_op.create_index('idx_analysis_created', ['created_at'], unique=False)

    op.create_table('fact_statements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=255), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=100), nullable=True),
    sa.Column('start_sec', sa.FLOAT(), nullable=True),
    sa.Column('end_sec', sa.FLOAT(), nullable=True),
    sa.Column('original_text', sa.TEXT(), nullable=False),
    sa.Column('clean_text', sa.TEXT(), nullable=False),
    sa.Column('topic_tag', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_names', sa.TEXT(), nullable=True),
    sa.Column('keywords', sa.TEXT(), nullable=True),
    sa.Column('sentence_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), nullable=True),
    sa.Column('word_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), server_default=sa.text('(0.8)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_statements', schema=None) as batch_op:
        batch_op.create_index('ix_fact_statements_topic_tag', ['topic_tag'], unique=False)
        batch_op.create_index('ix_fact_statements_speaker', ['speaker'], unique=False)
        batch_op.create_index('ix_fact_statements_source_file', ['source_file'], unique=False)
        batch_op.create_index('ix_fact_statements_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_fact_statements_id', ['id'], unique=False)
        batch_op.create_index('ix_fact_statements_document_id', ['document_id'], unique=False)
        batch_op.create_index('idx_fact_statements_unique', ['document_id', 'clean_text', 'chunk_index'], unique=1)
        batch_op.create_index('idx_fact_statements_topic', ['topic_tag'], unique=False)
        batch_op.create_index('idx_fact_statements_document', ['document_id'], unique=False)
        batch_op.create_index('idx_fact_statements_doc_topic', ['document_id', 'topic_tag'], unique=False)
        batch_op.create_index('idx_fact_statements_doc', ['document_id'], unique=False)
        batch_op.create_index('idx_fact_speaker', ['speaker'], unique=False)
        batch_op.create_index('idx_fact_project_topic', ['project_id', 'topic_tag'], unique=False)
        batch_op.create_index('idx_fact_document', ['document_id'], unique=False)

    op.create_table('structured_insights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('original_text', sa.TEXT(), nullable=False),
    sa.Column('cleaned_text', sa.TEXT(), nullable=False),
    sa.Column('topics', sa.VARCHAR(length=255), nullable=True),
    sa.Column('persons', sa.TEXT(), nullable=True),
    sa.Column('locations', sa.TEXT(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('word_count', sa.INTEGER(), nullable=True),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structured_insights', schema=None) as batch_op:
        batch_op.create_index('ix_structured_insights_topics', ['topics'], unique=False)
        batch_op.create_index('ix_structured_insights_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_structured_insights_id', ['id'], unique=False)
        batch_op.create_index('ix_structured_insights_document_id', ['document_id'], unique=False)

    op.drop_table('contexts')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
