"""Add pipeline state tables for v2 agents

Revision ID: fd1ee1e9d5d3
Revises: 003
Create Date: 2026-08-16 22:05:30.677321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fd1ee1e9d5d3'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('pipeline_mode', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_executions', schema=None) as batch_op:
        batch_op.create_index('idx_pipeline_created', ['created_at'], unique=False)
        batch_op.create_index('idx_pipeline_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_executions_execution_id'), ['execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pipeline_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_executions_project_id'), ['project_id'], unique=False)

    op.create_table('chunk_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk_entities', schema=None) as batch_op:
        batch_op.create_index('idx_chunk_entity', ['chunk_id', 'entity_id'], unique=False)
        batch_op.create_index('idx_entity_chunks', ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_entities_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_entities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_entities_id'), ['id'], unique=False)

    op.create_table('pipeline_stage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stage_data', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['pipeline_executions.execution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_stage_results', schema=None) as batch_op:
        batch_op.create_index('idx_stage_execution_name', ['execution_id', 'stage_name'], unique=False)
        batch_op.create_index('idx_stage_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stage_results_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stage_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stage_results_stage_name'), ['stage_name'], unique=False)

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index('idx_relation_subject_type')
        batch_op.drop_index('idx_relation_type_confidence')
        batch_op.drop_index('ix_relations_object_entity_id')
        batch_op.drop_index('ix_relations_relation_id')
        batch_op.drop_index('ix_relations_relation_type')
        batch_op.drop_index('ix_relations_subject_entity_id')

    op.drop_table('relations')
    with op.batch_alter_table('co_occurrences', schema=None) as batch_op:
        batch_op.drop_index('idx_cooccurrence_freq')

    op.drop_table('co_occurrences')
    with op.batch_alter_table('knowledge_graphs', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_graphs_graph_id')

    op.drop_table('knowledge_graphs')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('chunk_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chunking_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chunking_params', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('embedding_vector', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_document_chunks_chunk_id')
        batch_op.create_index('idx_chunk_document', ['document_id', 'chunk_index'], unique=False)
        batch_op.create_index('idx_chunk_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)
        # Skip foreign key constraint operations that cause issues with unnamed constraints
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'])
        batch_op.drop_column('prev_chunk_id')
        batch_op.drop_column('vectorized_at')
        batch_op.drop_column('chunk_metadata')
        batch_op.drop_column('chunk_id')
        batch_op.drop_column('next_chunk_id')
        batch_op.drop_column('text')
        batch_op.drop_column('text_length')
        batch_op.drop_column('embedding')
        batch_op.drop_column('end_pos')
        batch_op.drop_column('total_chunks')
        batch_op.drop_column('start_pos')

    with op.batch_alter_table('document_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_relations_id'), ['id'], unique=False)
        # Skip foreign key constraint operations that cause issues with unnamed constraints
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'documents', ['source_document_id'], ['id'])
        # batch_op.create_foreign_key(None, 'documents', ['target_document_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exif_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('entity_alignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_alignments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_alignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_alignments_id'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('exif_metadata')

    with op.batch_alter_table('document_relations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_documents', ['target_document_id'], ['id'])
        batch_op.create_foreign_key(None, 'project_documents', ['source_document_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_document_relations_id'))

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_pos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_chunks', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('end_pos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('text_length', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('next_chunk_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('chunk_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('chunk_metadata', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('vectorized_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('prev_chunk_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_documents', ['document_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))
        batch_op.drop_index('idx_chunk_project')
        batch_op.drop_index('idx_chunk_document')
        batch_op.create_index('ix_document_chunks_chunk_id', ['chunk_id'], unique=1)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('extra_metadata')
        batch_op.drop_column('embedding_vector')
        batch_op.drop_column('chunking_params')
        batch_op.drop_column('chunking_method')
        batch_op.drop_column('chunk_size')
        batch_op.drop_column('chunk_text')

    op.create_table('knowledge_graphs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('graph_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('entity_count', sa.INTEGER(), nullable=True),
    sa.Column('relation_count', sa.INTEGER(), nullable=True),
    sa.Column('document_count', sa.INTEGER(), nullable=True),
    sa.Column('statistics', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id')
    )
    with op.batch_alter_table('knowledge_graphs', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_graphs_graph_id', ['graph_id'], unique=False)

    op.create_table('co_occurrences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entities', sqlite.JSON(), nullable=False),
    sa.Column('frequency', sa.INTEGER(), nullable=True),
    sa.Column('window_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('co_occurrences', schema=None) as batch_op:
        batch_op.create_index('idx_cooccurrence_freq', ['frequency'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('relation_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject_entity_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('object_entity_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.FLOAT(), nullable=True),
    sa.Column('source_document', sa.VARCHAR(length=200), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index('ix_relations_subject_entity_id', ['subject_entity_id'], unique=False)
        batch_op.create_index('ix_relations_relation_type', ['relation_type'], unique=False)
        batch_op.create_index('ix_relations_relation_id', ['relation_id'], unique=False)
        batch_op.create_index('ix_relations_object_entity_id', ['object_entity_id'], unique=False)
        batch_op.create_index('idx_relation_type_confidence', ['relation_type', 'confidence'], unique=False)
        batch_op.create_index('idx_relation_subject_type', ['subject_entity_id', 'relation_type'], unique=False)

    with op.batch_alter_table('pipeline_stage_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_results_stage_name'))
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_results_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_results_execution_id'))
        batch_op.drop_index('idx_stage_status')
        batch_op.drop_index('idx_stage_execution_name')

    op.drop_table('pipeline_stage_results')
    with op.batch_alter_table('chunk_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunk_entities_id'))
        batch_op.drop_index(batch_op.f('ix_chunk_entities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_chunk_entities_chunk_id'))
        batch_op.drop_index('idx_entity_chunks')
        batch_op.drop_index('idx_chunk_entity')

    op.drop_table('chunk_entities')
    with op.batch_alter_table('pipeline_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_executions_project_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_executions_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_executions_execution_id'))
        batch_op.drop_index('idx_pipeline_project_status')
        batch_op.drop_index('idx_pipeline_created')

    op.drop_table('pipeline_executions')
    # ### end Alembic commands ###
