"""Add architecture upgrade models: permissions, audit, workflow, lineage, metrics, engagement

Revision ID: b65525f1a4d6
Revises: 008_add_tfidf_clustering
Create Date: 2026-08-29 14:29:18.214027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b65525f1a4d6'
down_revision: Union[str, None] = '008_add_tfidf_clustering'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.alter_column('target_entity_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('fact_statements', schema=None) as batch_op:
        batch_op.drop_index('idx_document_time')
        batch_op.drop_index('idx_project_time')
        batch_op.create_index('idx_federation_document_time', ['document_id', 'start_sec'], unique=False)
        batch_op.create_index('idx_federation_project_time', ['project_id', 'start_sec'], unique=False)

    with op.batch_alter_table('fieldmind_objects', schema=None) as batch_op:
        batch_op.create_index('idx_federation_fid_project', ['fid', 'project_id'], unique=False)
        batch_op.create_index('idx_federation_project_type', ['project_id', 'object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fieldmind_objects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fieldmind_objects_fid'), ['fid'], unique=True)
        batch_op.create_index(batch_op.f('ix_fieldmind_objects_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fieldmind_objects_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fieldmind_objects_source_fid'), ['source_fid'], unique=False)

    with op.batch_alter_table('object_relations', schema=None) as batch_op:
        batch_op.drop_index('idx_from_to')
        batch_op.drop_index('idx_from_type')
        batch_op.drop_index('idx_project_relation')
        batch_op.create_index('idx_federation_from_to', ['from_fid', 'to_fid'], unique=False)
        batch_op.create_index('idx_federation_from_type', ['from_fid', 'relation_type'], unique=False)
        batch_op.create_index('idx_federation_project_relation', ['project_id', 'relation_type'], unique=False)

    with op.batch_alter_table('project_document_tags', schema=None) as batch_op:
        batch_op.drop_index('uq_project_document_tags_document_name')

    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_index('uq_project_documents_project_hash')

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_type', sa.Enum('MANUAL', 'AUTO', 'RETRY', name='triggertype'), nullable=False))
        batch_op.add_column(sa.Column('triggered_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('progress_percentage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estimated_completion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'),
               nullable=False)
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_status'), ['status'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workflow_id')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('project_name')
        batch_op.drop_column('output_data')
        batch_op.drop_column('task_id')
        batch_op.drop_column('start_time')
        batch_op.drop_column('input_data')
        batch_op.drop_column('executed_by')
        batch_op.drop_column('step_results')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('step_results', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('executed_by', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('input_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('output_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('workflow_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['executed_by'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_workflow_executions_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_project_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('extra_metadata')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('estimated_completion')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('triggered_by')
        batch_op.drop_column('trigger_type')

    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.create_index('uq_project_documents_project_hash', ['project_id', 'file_hash'], unique=1)

    with op.batch_alter_table('project_document_tags', schema=None) as batch_op:
        batch_op.create_index('uq_project_document_tags_document_name', ['document_id', 'name'], unique=1)

    with op.batch_alter_table('object_relations', schema=None) as batch_op:
        batch_op.drop_index('idx_federation_project_relation')
        batch_op.drop_index('idx_federation_from_type')
        batch_op.drop_index('idx_federation_from_to')
        batch_op.create_index('idx_project_relation', ['project_id', 'relation_type'], unique=False)
        batch_op.create_index('idx_from_type', ['from_fid', 'relation_type'], unique=False)
        batch_op.create_index('idx_from_to', ['from_fid', 'to_fid'], unique=False)

    with op.batch_alter_table('fieldmind_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fieldmind_objects_source_fid'))
        batch_op.drop_index(batch_op.f('ix_fieldmind_objects_project_id'))
        batch_op.drop_index(batch_op.f('ix_fieldmind_objects_object_type'))
        batch_op.drop_index(batch_op.f('ix_fieldmind_objects_fid'))
        batch_op.drop_index(batch_op.f('ix_fieldmind_objects_created_at'))
        batch_op.drop_index('idx_federation_project_type')
        batch_op.drop_index('idx_federation_fid_project')

    with op.batch_alter_table('fact_statements', schema=None) as batch_op:
        batch_op.drop_index('idx_federation_project_time')
        batch_op.drop_index('idx_federation_document_time')
        batch_op.create_index('idx_project_time', ['project_id', 'start_sec'], unique=False)
        batch_op.create_index('idx_document_time', ['document_id', 'start_sec'], unique=False)

    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.alter_column('target_entity_id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
